name: bhawana_s_collection
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  sms_autofill: ^2.3.0
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Tenor Sans
      fonts: 
        - asset: assets/fonts/TenorSans.ttf
          weight: 400
